# https://regclient.org/usage/regsync/
sync:
  # Build base image
  - source: docker.io/hexpm/elixir:1.19.5-erlang-28.4.1-debian-trixie-20260316-slim
  - source: ghcr.io/cogini/elixir:1.19.5-erlang-28.4.1-debian-trixie-20260316-slim
    type: image
  # Build aws-otel-collector base image
  - source: docker.io/amazon/aws-otel-collector:latest
    target: ghcr.io/cogini/aws-otel-collector:latest
    type: image
  - source: docker.io/amazon/aws-otel-collector:v0.47.0
    target: ghcr.io/cogini/aws-otel-collector:v0.47.0
    type: image
  # Deploy base image
  - source: docker.io/debian:trixie-slim
    target: ghcr.io/cogini/debian:trixie-slim
    type: image
  - source: docker.io/debian:trixie-20260316-slim
    target: ghcr.io/cogini/debian:trixie-20260316-slim
    type: image
  # Test deps
  # https://hub.docker.com/_/postgres
  - source: docker.io/postgres:latest
    target: ghcr.io/cogini/pgvector:latest
    type: image
  - source: docker.io/postgres:18.3-alpine
    target: ghcr.io/cogini/postgres:18.3-alpine
    type: image
  # - source: docker.io/ankane/pgvector:latest
  #   target: ghcr.io/cogini/pgvector:latest
  #   type: image
  # - source: docker.io/ankane/pgvector:v0.5.1
  #   target: ghcr.io/cogini/pgvector:v0.5.1
  #   type: image
  # TODO: should use newer version from pgvector/pgvector instead of ankane/pgvector
  # https://hub.docker.com/r/pgvector/pgvector/tags
  - source: docker.io/rabbitmq:3-management
    target: ghcr.io/cogini/rabbitmq:3-management
    type: image
  - source: docker.io/rabbitmq:3.13.7-management
    target: ghcr.io/cogini/rabbitmq:3.13.7-management
    type: image
